import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));

function runReleaseFixture({ command, env = {}, bufferLimit }) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "vivi-release-output-"));
  try {
    let script = path.join(scriptDirectory, "run-release-step.mjs");
    if (bufferLimit !== undefined) {
      const source = fs.readFileSync(script, "utf8");
      const declaration = "const MAX_TRANSCRIPT_BUFFER_BYTES = 128 * 1024 * 1024;";
      expect(source.includes(declaration)).toBe(true);
      script = path.join(directory, "release-step-fixture.mjs");
      // Exercise the production script with only its cap reduced, not a new runtime option.
      fs.writeFileSync(
        script,
        source.replace(
          declaration,
          `const MAX_TRANSCRIPT_BUFFER_BYTES = ${bufferLimit};`,
        ),
      );
    }
    const result = spawnSync(
      process.execPath,
      [
        script,
        "--name",
        "output-fixture",
        "--",
        ...(typeof command === "function" ? command(directory) : command),
      ],
      {
        cwd: directory,
        encoding: "utf8",
        timeout: 15_000,
        env: { ...process.env, ...env },
      },
    );
    return {
      ...result,
      transcript: fs.readFileSync(
        path.join(directory, "transcripts/output-fixture.log"),
        "utf8",
      ),
    };
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
}

describe("generated WASM Gitleaks exception boundaries", () => {
  const config = fs.readFileSync(path.join(scriptDirectory, "../.gitleaks.toml"), "utf8");
  const generatedPath = "packages/runtime-wasm/src/native-wasm-bytes.ts";
  const evaluationPath = "packages/runtime-wasm/src/native-evaluation-wasm-bytes.ts";
  const pngPath = "packages/runtime-wasm/src/native-png-wasm-bytes.ts";
  const sections = config.replaceAll("\r\n", "\n").split(/^\[\[rules\]\]\n/m);
  const rules = sections.slice(1).map((source) => {
    const [header, ...blocks] = source.split(/^\[\[rules.allowlists\]\]\n/m);
    return {
      header: header.trim(),
      id: header.match(/^id = "([^"]+)"$/m)?.[1],
      blocks: blocks.map((block) => {
        const regexList = block.match(/^regexes = \[\n([\s\S]*?)^\]/m);
        return {
          source: block,
          condition: block.match(/^condition = "([^"]+)"$/m)?.[1],
          target: block.match(/^regexTarget = "([^"]+)"$/m)?.[1],
          path: block.match(/^paths = \['''([^']+)'''\]$/m)?.[1],
          regexList: regexList?.[1] ?? "",
          regexes: [...(regexList?.[1] ?? "").matchAll(/^ {2}'''([^']+)''',$/gm)].map(
            (match) => match[1],
          ),
          remainder: block
            .replace(/^description = "[^"\n]+"$/m, "")
            .replace(/^condition = "[^"]+"$/m, "")
            .replace(/^regexTarget = "[^"]+"$/m, "")
            .replace(/^paths = \['''[^']+'''\]$/m, "")
            .replace(/^regexes = \[\n[\s\S]*?^\]/m, "")
            .trim(),
        };
      }),
    };
  });
  // JS `$` also matches before a final newline; do not treat that as full membership.
  const wholeMatch = (expression, value) => {
    if (expression === undefined) return false;
    const match = new RegExp(expression).exec(value);
    return match?.index === 0 && match[0].length === value.length;
  };
  const allowed = (file, rule, match) =>
    rules.some(
      (entry) =>
        entry.id === rule &&
        entry.blocks.some(
          (block) =>
            block.condition === "AND" &&
            block.target === "match" &&
            wholeMatch(block.path, file) &&
            block.regexes.some((expression) => wholeMatch(expression, match)),
        ),
    );
  const chunk = "A".repeat(100);
  const separator = '",\n  "';
  const shapes = [
    `${"A".repeat(15)}${separator}${chunk}"`,
    `${"A".repeat(61)}${separator}${"A".repeat(20)}`,
    `${"A".repeat(10)}_${"A".repeat(17)}${separator}${chunk}"`,
    `${"A".repeat(6)}_${"A".repeat(3)}_A${separator}${chunk}"`,
  ];
  // Length/class fixtures only; never read generated bytes or decoded symbols.
  const regeneratedPrefixes = [
    { name: "raw eleven", lengths: [11] },
    { name: "one underscore", lengths: [10, 18] },
    { name: "four underscores", lengths: [6, 3, 9, 4, 14] },
    { name: "two underscores", lengths: [6, 3, 16] },
  ];
  const regeneratedShapes = regeneratedPrefixes.map(
    ({ lengths }) =>
      `${lengths.map((length) => "A".repeat(length)).join("_")}${separator}${chunk}"`,
  );

  it("retains default rules and exactly the reviewed closed rule-scoped blocks", () => {
    expect(sections[0]).toBe(
      'title = "Vivi2D Gitleaks configuration"\nminVersion = "8.30.1"\n\n[extend]\nuseDefault = true\n\n',
    );
    expect(rules.map((rule) => rule.header)).toEqual([
      'id = "generic-api-key"',
      'id = "square-access-token"',
    ]);
    expect(
      rules.flatMap((rule) =>
        rule.blocks.map((block) => [
          rule.id,
          block.condition,
          block.target,
          block.path,
          block.regexes.length,
        ]),
      ),
    ).toEqual([
      [
        "generic-api-key",
        "AND",
        "match",
        "^packages/runtime-wasm/src/native-wasm-bytes\\.ts$",
        8,
      ],
      [
        "generic-api-key",
        "AND",
        "match",
        "^packages/runtime-wasm/src/native-evaluation-wasm-bytes\\.ts$",
        21,
      ],
      [
        "generic-api-key",
        "AND",
        "match",
        "^packages/runtime-wasm/src/native-png-wasm-bytes\\.ts$",
        18,
      ],
      [
        "square-access-token",
        "AND",
        "match",
        "^packages/runtime-wasm/src/native-png-wasm-bytes\\.ts$",
        1,
      ],
    ]);
    for (const rule of rules) {
      for (const block of rule.blocks) {
        expect(block.remainder).toBe("");
        expect(block.regexList.trim().split("\n")).toHaveLength(block.regexes.length);
        expect(
          block.regexes.every(
            (expression) => expression.startsWith("^") && expression.endsWith("$"),
          ),
        ).toBe(true);
      }
    }
  });

  it("accepts only the reviewed generated chunk match shapes", () => {
    for (const shape of [...shapes, ...regeneratedShapes]) {
      expect(allowed(generatedPath, "generic-api-key", shape)).toBe(true);
      expect(allowed("other/native-wasm-bytes.ts", "generic-api-key", shape)).toBe(false);
      expect(allowed(`${generatedPath}.backup`, "generic-api-key", shape)).toBe(false);
      expect(allowed(generatedPath, "github-pat", shape)).toBe(false);
      expect(allowed(generatedPath, "generic-api-key", `prefix ${shape}`)).toBe(false);
      expect(allowed(generatedPath, "generic-api-key", `${shape} suffix`)).toBe(false);
    }
  });

  it("rejects unreviewed regenerated lengths, alphabets, and separators", () => {
    for (const { lengths } of regeneratedPrefixes) {
      const prefix = lengths.map((length) => "A".repeat(length)).join("_");
      const shape = `${prefix}${separator}${chunk}"`;
      for (let index = 0; index < lengths.length; index++) {
        for (const delta of [-1, 1]) {
          const nearLengths = [...lengths];
          nearLengths[index] += delta;
          const nearPrefix = nearLengths.map((length) => "A".repeat(length)).join("_");
          const nearShape = `${nearPrefix}${separator}${chunk}"`;
          // a10_a17 is intentionally retained by the older reviewed shape.
          if (shapes.includes(nearShape)) continue;
          expect(allowed(generatedPath, "generic-api-key", nearShape)).toBe(false);
        }
      }
      for (const malformed of [
        `${prefix}${separator}${"A".repeat(99)}"`,
        `${prefix}${separator}${"A".repeat(101)}"`,
        ...["+", "/", "-", ".", "_", "!"].map(
          (character) => `${character}${shape.slice(1)}`,
        ),
        `${prefix}${separator}_${chunk.slice(1)}"`,
        `${prefix}${separator}${chunk.slice(0, -1)}="`,
        shape.replace(separator, '";\n  "'),
        shape.replace(separator, '",\n "'),
        shape.replace(separator, '",\r\n  "'),
        `\n${shape}`,
        `${shape}\nextra`,
        `api_key = ${shape}`,
        `token: ${shape}`,
      ]) {
        expect(allowed(generatedPath, "generic-api-key", malformed)).toBe(false);
      }
    }
  });

  it("does not exempt credential assignments or wider chunk layouts in that file", () => {
    const syntheticValue = ["Q2w4E6r8", "T1y3U5i7", "O9p0A2s4", "D6f8G1h3"].join("");
    for (const field of ["api_key", "token", "password"]) {
      for (const operator of [" = ", ": "]) {
        expect(
          allowed(
            generatedPath,
            "generic-api-key",
            `${field}${operator}"${syntheticValue}"`,
          ),
        ).toBe(false);
      }
    }
    for (const malformed of [
      `${"A".repeat(14)}${separator}${chunk}"`,
      `${"A".repeat(74)}${separator}${chunk}"`,
      `${"A".repeat(61)}${separator}${"A".repeat(101)}`,
      `${"A".repeat(61)}${separator}${"A".repeat(9)}`,
      `${"A".repeat(11)}_${"A".repeat(17)}${separator}${chunk}"`,
      shapes[2].replace("\n  ", "\n    "),
    ]) {
      expect(allowed(generatedPath, "generic-api-key", malformed)).toBe(false);
    }
  });

  // Independent reviewed membership tables, not values extracted from the regexes.
  const rawLengths = new Map([
    [generatedPath, [11, ...Array.from({ length: 59 }, (_, index) => index + 15)]],
    [
      evaluationPath,
      [9, 20, 25, 27, 28, 30, 31, 53, 54, 56, 57, 60, 61, 62, 64, 65, 68, 69, 72, 73],
    ],
    [pngPath, [12, 19, 20, 27, 32, 53, 56, 57, 60, 61, 62, 64, 65, 68, 69, 72, 73]],
  ]);
  const decodedLengths = new Map([
    [
      generatedPath,
      [
        [10, 17],
        [6, 3, 1],
        [10, 18],
        [6, 3, 9, 4, 14],
        [6, 3, 16],
      ],
    ],
    [evaluationPath, [[6, 3, 0]]],
    [pngPath, [[6, 3, 9, 4, 1]]],
  ]);
  const completeShape = (prefix) => `${prefix}${separator}${chunk}"`;

  it("checks 306 raw lengths and 306 truncated-chunk memberships against fixed sets", () => {
    for (const [file, lengths] of rawLengths) {
      for (let length = 0; length <= 101; length++) {
        expect(allowed(file, "generic-api-key", completeShape("A".repeat(length)))).toBe(
          lengths.includes(length),
        );
        const truncated = `${"A".repeat(61)}${separator}${"A".repeat(length)}`;
        expect(allowed(file, "generic-api-key", truncated)).toBe(
          file === generatedPath && length >= 10 && length <= 100,
        );
      }
    }
  });

  it("checks decoded tuple mutations across all paths without rejecting approved overlap", () => {
    const tuples = [...decodedLengths.values()].flat();
    for (const tuple of tuples) {
      const candidates = [tuple];
      for (let index = 0; index < tuple.length; index++) {
        for (const delta of [-1, 1]) {
          if (tuple[index] + delta < 0) continue;
          const changed = [...tuple];
          changed[index] += delta;
          candidates.push(changed);
        }
      }
      for (const candidate of candidates) {
        const prefix = candidate.map((length) => "A".repeat(length)).join("_");
        for (const [file, approved] of decodedLengths) {
          const expected = approved.some(
            (lengths) => JSON.stringify(lengths) === JSON.stringify(candidate),
          );
          expect(allowed(file, "generic-api-key", completeShape(prefix))).toBe(expected);
        }
      }
    }
    // [6,3,0] includes the trailing underscore; it is not an optional suffix.
    expect(allowed(evaluationPath, "generic-api-key", completeShape("AAAAAA_AAA"))).toBe(
      false,
    );
    expect(
      allowed(evaluationPath, "generic-api-key", completeShape("AAAAAA_AAA_A")),
    ).toBe(false);
    expect(allowed(generatedPath, "generic-api-key", completeShape("AAAAAA_AAA_A"))).toBe(
      true,
    );
  });

  it("bounds every new shape by rule, path, alphabet and exact chunk layout", () => {
    for (const file of [evaluationPath, pngPath]) {
      const rawPrefixes = rawLengths.get(file).map((length) => "A".repeat(length));
      const decodedPrefixes = decodedLengths
        .get(file)
        .map((tuple) => tuple.map((length) => "A".repeat(length)).join("_"));
      for (const prefix of [...rawPrefixes, ...decodedPrefixes]) {
        const shape = completeShape(prefix);
        expect(allowed(file, "generic-api-key", shape)).toBe(true);
        for (const wrongFile of [
          path.basename(file),
          `other/${file}`,
          `${file}.backup`,
          `${file}\n`,
          "src/generated-security-control.ts",
        ]) {
          expect(allowed(wrongFile, "generic-api-key", shape)).toBe(false);
        }
        for (const wrongRule of ["square-access-token", "github-pat", "unknown-rule"]) {
          expect(allowed(file, wrongRule, shape)).toBe(false);
        }
        for (const character of ["+", "/"]) {
          expect(
            allowed(file, "generic-api-key", completeShape(character + prefix.slice(1))),
          ).toBe(!prefix.includes("_"));
        }
        for (const malformed of [
          ...["-", ".", "_", "!", "="].map((character) => character + shape.slice(1)),
          `${prefix}${separator}${"A".repeat(99)}"`,
          `${prefix}${separator}${"A".repeat(101)}"`,
          `${prefix}${separator}_${chunk.slice(1)}"`,
          `${prefix}${separator}${chunk.slice(0, -1)}="`,
          shape.replace(separator, '";\n  "'),
          shape.replace(separator, '",\n "'),
          shape.replace(separator, '",\n    "'),
          shape.replace(separator, '",\r\n  "'),
          `prefix ${shape}`,
          `${shape} suffix`,
          `\n${shape}`,
          `${shape}\n`,
          `api_key = ${shape}`,
        ]) {
          expect(allowed(file, "generic-api-key", malformed)).toBe(false);
        }
      }
    }
  });

  it("keeps the Square exception exact, hex-escaped, rule-scoped and PNG-only", () => {
    // Fixed benign compiler-output witness, assembled independently of its regex.
    const squareMatch =
      String.fromCharCode(0x45) +
      'AAAAAAgIQuQQAAAADQEmNBAAAAAITXl0EAAAAAZc3NQQAAACBfoAJCAAAA"';
    expect(squareMatch).toHaveLength(60);
    expect(createHash("sha256").update(squareMatch).digest("hex")).toBe(
      "c295a85082182cf4e11342dec0d80438aa61b0e3a2ed4835f0d05f404463df73",
    );
    expect(rules[1].blocks[0].regexes[0].startsWith("^\\x45")).toBe(true);
    for (const file of [
      generatedPath,
      evaluationPath,
      pngPath,
      "src/generated-security-control.ts",
    ]) {
      expect(allowed(file, "square-access-token", squareMatch)).toBe(file === pngPath);
      expect(allowed(file, "generic-api-key", squareMatch)).toBe(false);
      expect(allowed(file, "github-pat", squareMatch)).toBe(false);
    }
    for (const malformed of [
      `\\x45${squareMatch.slice(1)}`,
      `${squareMatch.slice(0, -2)}Z"`,
      squareMatch.slice(1),
      squareMatch.slice(0, -1),
      `prefix ${squareMatch}`,
      `${squareMatch} suffix`,
      `${squareMatch}\n`,
      `\n${squareMatch}`,
    ]) {
      expect(allowed(pngPath, "square-access-token", malformed)).toBe(false);
    }
  });

  it("does not exempt plaintext or encoded synthetic credentials on generated paths", () => {
    const value = ["Q2w4E6r8", "T1y3U5i7", "O9p0A2s4", "D6f8G1h3"].join("");
    const github = ["gh", "p_", value, "N8m6"].join("");
    const square =
      String.fromCharCode(0x45) +
      "AAAAAAgIQuQQAAAADQEmNBAAAAAITXl0EAAAAAZc3NQQAAACBfoAJCAAAZ";
    for (const file of [...rawLengths.keys(), "src/generated-security-control.ts"]) {
      for (const [rule, token] of [
        ["generic-api-key", value],
        ["github-pat", github],
        ["square-access-token", square],
      ]) {
        const assignment = `api_key = "${token}"`;
        for (const candidate of [
          token,
          `${token}"`,
          assignment,
          Buffer.from(assignment).toString("base64"),
        ]) {
          expect(allowed(file, rule, candidate)).toBe(false);
        }
      }
    }
    // These are allowlist membership tests. Actual scanner witnesses are separate:
    // the detector may omit assignment context or decode encoded source first.
  });
});

describe("secret checker diagnostic redaction", () => {
  for (const status of [0, 7]) {
    it(`redacts complete and split child output on exit ${status}`, () => {
      const markers = [
        ["gh", "p_", "Q".repeat(36)].join(""),
        ["sk-", "proj-", "R".repeat(36)].join(""),
      ];
      const delay = status === 0 ? 5_200 : 25;
      const childSource = `
        const markers = JSON.parse(process.env.VIVI_REDACTION_FIXTURES);
        const streams = [process.stdout, process.stderr];
        streams.forEach((stream, index) => {
          stream.write("ordinary output\\n" + markers[index] + "\\n");
          stream.write(markers[index].slice(0, 8));
        });
        setTimeout(() => {
          streams.forEach((stream, index) => stream.write(markers[index].slice(8) + "\\n"));
          process.exitCode = ${status};
        }, ${delay});
      `;
      const result = runReleaseFixture({
        command: [process.execPath, "-e", childSource],
        env: {
          VIVI_REDACTION_FIXTURES: JSON.stringify(markers),
          VIVI2D_RELEASE_STEP_HEARTBEAT_MS: "5000",
        },
      });
      expect(result.status).toBe(status);
      for (const text of [result.stdout + result.stderr, result.transcript]) {
        for (const marker of markers) {
          expect(text.includes(marker.slice(0, 8))).toBe(false);
          expect(text.includes(marker.slice(-8))).toBe(false);
        }
        expect(text.includes("ordinary output")).toBe(true);
        expect(text.includes("<github-token-redacted>")).toBe(true);
        expect(text.includes("<openai-key-redacted>")).toBe(true);
      }
      if (status === 0) expect(result.stderr.includes("still running;")).toBe(true);
    }, 20_000);
  }

  it("omits dynamic command arguments from transcript metadata", () => {
    const marker = ["non-authentic-", "command-argument"].join("");
    const result = runReleaseFixture({
      command: [process.execPath, "-e", "", "--", marker],
    });
    expect(result.status).toBe(0);
    expect((result.stdout + result.stderr + result.transcript).includes(marker)).toBe(
      false,
    );
    expect(
      result.transcript.includes("command: <omitted; see named workflow step>"),
    ).toBe(true);
  });

  it("reports spawn failures without reflecting the executable path", () => {
    const marker = ["non-authentic-", "missing-executable"].join("");
    const result = runReleaseFixture({
      command: (directory) => [path.join(directory, marker)],
    });
    expect(result.status).not.toBe(0);
    expect((result.stdout + result.stderr + result.transcript).includes(marker)).toBe(
      false,
    );
    expect(result.stderr.includes("child process could not be started")).toBe(true);
  });

  it("drops the incomplete final line at the transcript byte cap", () => {
    const marker = ["gh", "p_", "Q".repeat(36)].join("");
    const result = runReleaseFixture({
      command: [
        process.execPath,
        "-e",
        'process.stdout.write("ordinary output\\n" + process.env.VIVI_REDACTION_FIXTURE);',
      ],
      env: { VIVI_REDACTION_FIXTURE: marker },
      bufferLimit: 24,
    });
    expect(result.status).toBe(0);
    for (const text of [result.stdout + result.stderr, result.transcript]) {
      expect(text.includes(marker.slice(0, 8))).toBe(false);
      expect(text.includes("ordinary output")).toBe(true);
      expect(text.includes("transcript truncated")).toBe(true);
    }
  });

  it("preserves npm environment labels when redacting saved release transcripts", () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), "vivi-release-redaction-"));
    try {
      const marker = ["non-authentic-", "fixture-value"].join("");
      const childSource =
        'for (const label of ["NPM_TOKEN", "NODE_AUTH_TOKEN"]) console.log(label + "=" + process.env.VIVI_REDACTION_FIXTURE);';
      const result = spawnSync(
        process.execPath,
        [
          path.join(scriptDirectory, "run-release-step.mjs"),
          "--name",
          "redaction-fixture",
          "--",
          process.execPath,
          "-e",
          childSource,
        ],
        {
          cwd: directory,
          encoding: "utf8",
          env: { ...process.env, VIVI_REDACTION_FIXTURE: marker },
        },
      );
      expect(result.status).toBe(0);
      const transcript = fs.readFileSync(
        path.join(directory, "transcripts/redaction-fixture.log"),
        "utf8",
      );
      expect(transcript.includes(marker)).toBe(false);
      expect(transcript.includes("NPM_TOKEN=<redacted>")).toBe(true);
      expect(transcript.includes("NODE_AUTH_TOKEN=<redacted>")).toBe(true);
      expect(transcript.includes("$1=<redacted>")).toBe(false);
      expect((result.stdout + result.stderr).includes(marker)).toBe(false);
    } finally {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });

  for (const script of ["check-secrets.mjs", "check-history-secrets.mjs"]) {
    it(`${script} reports location without credential fragments`, () => {
      const directory = fs.mkdtempSync(path.join(os.tmpdir(), "vivi-secret-redaction-"));
      try {
        const git = (...args) => {
          const result = spawnSync("git", args, { cwd: directory, encoding: "utf8" });
          expect(result.status).toBe(0);
        };
        git("init", "--template=");
        // Synthetic, deliberately non-authentic credential shape; never contact a service.
        const marker = ["gh", "p_", "Q".repeat(36)].join("");
        fs.writeFileSync(path.join(directory, "fixture.txt"), marker);
        git("add", "fixture.txt");
        git(
          "-c",
          "user.name=Redaction Test",
          "-c",
          "user.email=redaction@example.invalid",
          "-c",
          "commit.gpgsign=false",
          "-c",
          "core.hooksPath=.no-hooks",
          "commit",
          "--no-verify",
          "-m",
          "Synthetic fixture",
        );
        const result = spawnSync(process.execPath, [path.join(scriptDirectory, script)], {
          cwd: directory,
          encoding: "utf8",
        });
        const output = result.stdout + result.stderr;
        expect(result.status).toBe(1);
        expect(output.includes("fixture.txt:1: GitHub token")).toBe(true);
        expect(output.includes(marker.slice(0, 6))).toBe(false);
        expect(output.includes(marker.slice(-4))).toBe(false);
        expect(output.includes("[REDACTED]")).toBe(true);
      } finally {
        // Only the exact directory created by this test is removed.
        fs.rmSync(directory, { recursive: true, force: true });
      }
    });
  }
});
